version: "3.9"

services:
  flask-app:
    # Where to build from in our docker container
    build:
      context: ./backend
    # Name the container
    container_name: backend
    # Map the ports that we expose to our local port
    ports:
      - "5000:5000"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  celery-worker:
    build:
      context: ./backend
    container_name: celery-worker
    command: celery -A app.celery worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"
