# "version" is now obsolete

services:
  flask-app:
    # Where to build from in our docker container
    build:
      context: ./backend
    # This will automatically read variables from the .env file
    env_file:
      - /backend/.env
    # Name the container
    container_name: backend
    # Map the ports that we expose to our local port
    ports:
      - "5000:5000"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    volumes: # Bind mount for live code updates
      - ./backend:/app

  celery-worker:
    build:
      context: ./backend
    env_file:
      - /backend/.env
    container_name: celery-worker
    command: celery -A app.celery worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes: # Bind mount for live code updates
      - ./backend:/app
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - flask-app

  redis:
    image: "redis/redis-stack-server:latest"
    container_name: redis
    ports:
      - "6379:6379"
